### ISSUE TITLE
群组积分

### ISSUE THREAD

**Issue by arron2345** [BNB48Club/BNB48_bot#48]
目前已经管理了近几十个群，但是如果开通积分功能的话，应该是按照单个群来计算的，要求：

1. 通过命令触发积分功能
2. 单个群的积分单独运算
3. 积分定期（1个月）清零（当然，中文群如果想跟 KOGI积分打通，可以另外 探讨个模式）
4. 群内无感知计算（不需要在群里发送提醒，某个用户得到几个积分，这样的消息）
5. 通过特定命令触发排行榜（排名前10的，处于排名10以外的，在最后一行提示该用户多少名），注意：需要剔除管理员参与积分的权限。
6. 某用户触发规则被ban，清零积分。

**Comment by BNB48ClubSirIan** [comment]
@arron2345 我觉得可以考虑一下各群社区积分互通。
不通的话数据格式会搞得比较复杂
通了不是更有大联盟的感觉吗？

**Comment by arron2345** [comment]
1. 社群积分为什么单个统计是基于不同的社区或者语言，互通的话，对别的非群人员，也没有任何借鉴的意义，比如如果我按照月度排名，前10的人送周边，那么如果是小语种的群，比如越南土耳其的，那么可能前10就没他们的名字，比较尴尬。
2. 不是所有的社群都愿意开通积分的，所以只在能够愿意接纳积分的社群里面推广，比如某个社群要单独搞一个活动，就触发积分功能。
3. 大联盟的数据想法很好，但是我觉得暂时应该不用往这个方向去做。

**Comment by BNB48ClubSirIan** [comment]
积分功能默认开启
每个群独立计算
points 查看自己的积分
rank 查看本群前十(需要管理员权限)
clearpoints 清零所有本群积分(需要管理员权限)

由于机器人暂时没有接管ban功能，所以被ban清零暂不添加。
