### ISSUE TITLE
积分红包随机送

### ISSUE THREAD

**Issue by arron2345** [BNB48Club/BNB48_bot#60]
1. 在某一段时间内开启 积分随机送功能；
2. 群里触发 /命令词，随机奉送积分（比如： /恭喜发财），每人每天限触发一次，二次触发时，提示已经触发，并在5分钟后，删除触发的命令与回复，避免大量垃圾信息。

注意：由于涉及多语言社群，建议通过命令进行开启，
输入 /activity 创建新活动
输入 群ID xxxxxxxxxxxx 为某群创建活动
输入 /springfestival 创建活动名称，并开启该群活动
输入 20XX/XX/XX XX:XX - 20XX/XX/XX XX:XX 确定活动时间。

3. 活动时间内，按照随机金额积分+聊天送的积分，进行排名。

**Comment by BNB48ClubSirIan** [comment]
随机奉送多少？服从什么分布？ 积分从谁那里扣？
活动目的是啥? 
5分钟够把客户端刷死机了

**Comment by arron2345** [comment]
设定一个基数，比如一天1000分，随机分配一个数值，因为不能保障有多少人触发，所以，要选择一个随机系数，但是分值不能相差太大，比如随机分值在0.1分到2分之间。随机给1个值就可以了。
活动目的，就是引入红包概念，新年图一个吉利乐呵。
如果命令只在一个群运行，应该还好，不会把机器人干趴下吧。

**Comment by BNB48ClubSirIan** [comment]
/bonuscode xxxxx 增加红包词，随机赠送1-5积分
激活之后下一个UTC0点失效

红包词仅在本群开通了聊天积分时有效
